// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/hsi.proto

package hsi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Ts            string                 `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Source        *Source                `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Session       *Session               `protobuf:"bytes,5,opt,name=session,proto3" json:"session,omitempty"`
	Signal        *Signal                `protobuf:"bytes,6,opt,name=signal,proto3" json:"signal,omitempty"`
	Meta          *Meta                  `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_hsi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hsi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_hsi_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *Event) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Event) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *Event) GetSignal() *Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

func (x *Event) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Side          *string                `protobuf:"bytes,3,opt,name=side,proto3,oneof" json:"side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_proto_hsi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hsi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_proto_hsi_proto_rawDescGZIP(), []int{1}
}

func (x *Source) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Source) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Source) GetSide() string {
	if x != nil && x.Side != nil {
		return *x.Side
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Scenario      string                 `protobuf:"bytes,2,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Seed          int64                  `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_hsi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hsi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_hsi_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Session) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *Session) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type Signal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Value         *SignalValue           `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Quality       float64                `protobuf:"fixed64,4,opt,name=quality,proto3" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_proto_hsi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hsi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_proto_hsi_proto_rawDescGZIP(), []int{3}
}

func (x *Signal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Signal) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Signal) GetValue() *SignalValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Signal) GetQuality() float64 {
	if x != nil {
		return x.Quality
	}
	return 0
}

// signal value can be scalar, string, or vector
type SignalValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*SignalValue_Scalar
	//	*SignalValue_Text
	//	*SignalValue_Vector
	Kind          isSignalValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalValue) Reset() {
	*x = SignalValue{}
	mi := &file_proto_hsi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalValue) ProtoMessage() {}

func (x *SignalValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hsi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalValue.ProtoReflect.Descriptor instead.
func (*SignalValue) Descriptor() ([]byte, []int) {
	return file_proto_hsi_proto_rawDescGZIP(), []int{4}
}

func (x *SignalValue) GetKind() isSignalValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *SignalValue) GetScalar() float64 {
	if x != nil {
		if x, ok := x.Kind.(*SignalValue_Scalar); ok {
			return x.Scalar
		}
	}
	return 0
}

func (x *SignalValue) GetText() string {
	if x != nil {
		if x, ok := x.Kind.(*SignalValue_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *SignalValue) GetVector() *Vector3 {
	if x != nil {
		if x, ok := x.Kind.(*SignalValue_Vector); ok {
			return x.Vector
		}
	}
	return nil
}

type isSignalValue_Kind interface {
	isSignalValue_Kind()
}

type SignalValue_Scalar struct {
	Scalar float64 `protobuf:"fixed64,1,opt,name=scalar,proto3,oneof"`
}

type SignalValue_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type SignalValue_Vector struct {
	Vector *Vector3 `protobuf:"bytes,3,opt,name=vector,proto3,oneof"`
}

func (*SignalValue_Scalar) isSignalValue_Kind() {}

func (*SignalValue_Text) isSignalValue_Kind() {}

func (*SignalValue_Vector) isSignalValue_Kind() {}

type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_proto_hsi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hsi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_proto_hsi_proto_rawDescGZIP(), []int{5}
}

func (x *Vector3) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_proto_hsi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hsi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_proto_hsi_proto_rawDescGZIP(), []int{6}
}

func (x *Meta) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_proto_hsi_proto protoreflect.FileDescriptor

const file_proto_hsi_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/hsi.proto\x12\x03hsi\"\xea\x01\n" +
	"\x05Event\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\tR\x02ts\x12#\n" +
	"\x06source\x18\x04 \x01(\v2\v.hsi.SourceR\x06source\x12&\n" +
	"\asession\x18\x05 \x01(\v2\f.hsi.SessionR\asession\x12#\n" +
	"\x06signal\x18\x06 \x01(\v2\v.hsi.SignalR\x06signal\x12\x1d\n" +
	"\x04meta\x18\a \x01(\v2\t.hsi.MetaR\x04meta\"N\n" +
	"\x06Source\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x17\n" +
	"\x04side\x18\x03 \x01(\tH\x00R\x04side\x88\x01\x01B\a\n" +
	"\x05_side\"P\n" +
	"\aSession\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1a\n" +
	"\bscenario\x18\x02 \x01(\tR\bscenario\x12\x12\n" +
	"\x04seed\x18\x03 \x01(\x03R\x04seed\"r\n" +
	"\x06Signal\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12&\n" +
	"\x05value\x18\x03 \x01(\v2\x10.hsi.SignalValueR\x05value\x12\x18\n" +
	"\aquality\x18\x04 \x01(\x01R\aquality\"m\n" +
	"\vSignalValue\x12\x18\n" +
	"\x06scalar\x18\x01 \x01(\x01H\x00R\x06scalar\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x12&\n" +
	"\x06vector\x18\x03 \x01(\v2\f.hsi.Vector3H\x00R\x06vectorB\x06\n" +
	"\x04kind\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\"\"\n" +
	"\x04Meta\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequenceB5Z3github.com/synheart/synheart-cli/internal/proto/hsib\x06proto3"

var (
	file_proto_hsi_proto_rawDescOnce sync.Once
	file_proto_hsi_proto_rawDescData []byte
)

func file_proto_hsi_proto_rawDescGZIP() []byte {
	file_proto_hsi_proto_rawDescOnce.Do(func() {
		file_proto_hsi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hsi_proto_rawDesc), len(file_proto_hsi_proto_rawDesc)))
	})
	return file_proto_hsi_proto_rawDescData
}

var file_proto_hsi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_hsi_proto_goTypes = []any{
	(*Event)(nil),       // 0: hsi.Event
	(*Source)(nil),      // 1: hsi.Source
	(*Session)(nil),     // 2: hsi.Session
	(*Signal)(nil),      // 3: hsi.Signal
	(*SignalValue)(nil), // 4: hsi.SignalValue
	(*Vector3)(nil),     // 5: hsi.Vector3
	(*Meta)(nil),        // 6: hsi.Meta
}
var file_proto_hsi_proto_depIdxs = []int32{
	1, // 0: hsi.Event.source:type_name -> hsi.Source
	2, // 1: hsi.Event.session:type_name -> hsi.Session
	3, // 2: hsi.Event.signal:type_name -> hsi.Signal
	6, // 3: hsi.Event.meta:type_name -> hsi.Meta
	4, // 4: hsi.Signal.value:type_name -> hsi.SignalValue
	5, // 5: hsi.SignalValue.vector:type_name -> hsi.Vector3
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_hsi_proto_init() }
func file_proto_hsi_proto_init() {
	if File_proto_hsi_proto != nil {
		return
	}
	file_proto_hsi_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_hsi_proto_msgTypes[4].OneofWrappers = []any{
		(*SignalValue_Scalar)(nil),
		(*SignalValue_Text)(nil),
		(*SignalValue_Vector)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hsi_proto_rawDesc), len(file_proto_hsi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_hsi_proto_goTypes,
		DependencyIndexes: file_proto_hsi_proto_depIdxs,
		MessageInfos:      file_proto_hsi_proto_msgTypes,
	}.Build()
	File_proto_hsi_proto = out.File
	file_proto_hsi_proto_goTypes = nil
	file_proto_hsi_proto_depIdxs = nil
}
